"""mcp-sdk-py — Model Context Protocol SDK for Python.

Wave 1 (S01): protocol foundations and conformance model.
Wave 2 (S02, S20, S43): JSON value model, common data types, lifecycle.
"""

from mcp_sdk_py.foundations import (
  CONFORMANCE_BASELINE,
  ConformanceError,
  DeprecationStatus,
  Implementation,
  MessageKind,
  MissingCapabilityError,
  RequirementLevel,
  Role,
)
from mcp_sdk_py.common_types import (
  ALLOWED_ICON_SCHEMES,
  SUPPORTED_MIME_TYPES,
  SUPPORTED_MIME_TYPES_RECOMMENDED,
  SUPPORTED_MIME_TYPES_REQUIRED,
  UNSAFE_ICON_SCHEMES,
  BaseMetadata,
  Icon,
  IconTheme,
  validate_icon_src,
)
from mcp_sdk_py.json_value import (
  BASE_METHOD_NAMES,
  RESERVED_SECOND_LABELS,
  SAFE_INTEGER_MAX,
  SAFE_INTEGER_MIN,
  W3C_TRACE_KEYS,
  EnumerationPolicy,
  ExtensionNotSupportedError,
  JSONArray,
  JSONObject,
  JSONValue,
  UnknownEnumerationValueError,
  decode_utf8_json,
  encode_as_utf8,
  handle_unknown_enum_value,
  is_base_method_name,
  is_integer_value,
  is_reserved_meta_prefix,
  is_valid_meta_label,
  is_valid_meta_name,
  is_valid_meta_prefix,
  is_within_safe_range,
  last_occurrence_wins,
  names_match,
  numbers_are_equal,
  parse_meta_key,
  preserve_unknown_keys,
  strip_unknown_keys,
  validate_extension_method_name,
  validate_integer_field,
  validate_meta_key_grammar,
  validate_meta_key_not_reserved,
  validate_safe_integer,
)
from mcp_sdk_py.lifecycle import (
  DEPRECATED_FEATURE_NAMES,
  DEPRECATED_FEATURES_REGISTRY,
  EXTENSION_LIFECYCLE_IS_INDEPENDENT,
  MINIMUM_DEPRECATION_WINDOW_DAYS,
  MINIMUM_EXPEDITED_WINDOW_DAYS,
  DeprecatedRegistryEntry,
  LifecycleError,
  LifecycleRecord,
  LifecycleState,
  can_transition,
  compute_deprecation_window_days,
  deprecated_feature,
  is_deprecated_feature,
  is_eligible_for_removal,
  validate_transition,
  warn_deprecated_feature,
)

__all__ = [
  # S01 — foundations
  "CONFORMANCE_BASELINE",
  "ConformanceError",
  "DeprecationStatus",
  "Implementation",
  "MessageKind",
  "MissingCapabilityError",
  "RequirementLevel",
  "Role",
  # S02 — JSON value model
  "BASE_METHOD_NAMES",
  "EnumerationPolicy",
  "ExtensionNotSupportedError",
  "JSONArray",
  "JSONObject",
  "JSONValue",
  "RESERVED_SECOND_LABELS",
  "SAFE_INTEGER_MAX",
  "SAFE_INTEGER_MIN",
  "UnknownEnumerationValueError",
  "W3C_TRACE_KEYS",
  "decode_utf8_json",
  "encode_as_utf8",
  "handle_unknown_enum_value",
  "is_base_method_name",
  "is_integer_value",
  "is_reserved_meta_prefix",
  "is_valid_meta_label",
  "is_valid_meta_name",
  "is_valid_meta_prefix",
  "is_within_safe_range",
  "last_occurrence_wins",
  "names_match",
  "numbers_are_equal",
  "parse_meta_key",
  "preserve_unknown_keys",
  "strip_unknown_keys",
  "validate_extension_method_name",
  "validate_integer_field",
  "validate_meta_key_grammar",
  "validate_meta_key_not_reserved",
  "validate_safe_integer",
  # S20 — common data types
  "ALLOWED_ICON_SCHEMES",
  "BaseMetadata",
  "Icon",
  "IconTheme",
  "SUPPORTED_MIME_TYPES",
  "SUPPORTED_MIME_TYPES_RECOMMENDED",
  "SUPPORTED_MIME_TYPES_REQUIRED",
  "UNSAFE_ICON_SCHEMES",
  "validate_icon_src",
  # S43 — lifecycle
  "DEPRECATED_FEATURE_NAMES",
  "DEPRECATED_FEATURES_REGISTRY",
  "EXTENSION_LIFECYCLE_IS_INDEPENDENT",
  "MINIMUM_DEPRECATION_WINDOW_DAYS",
  "MINIMUM_EXPEDITED_WINDOW_DAYS",
  "DeprecatedRegistryEntry",
  "LifecycleError",
  "LifecycleRecord",
  "LifecycleState",
  "can_transition",
  "compute_deprecation_window_days",
  "deprecated_feature",
  "is_deprecated_feature",
  "is_eligible_for_removal",
  "validate_transition",
  "warn_deprecated_feature",
]
